server:
  port: 8080
  tomcat:
    basedir: /tmp
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.9.121:3306/wpct?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: wpct
    password: 123456
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  main:
    allow-circular-references: true
  redis:
    host: 124.71.9.121
    port: 6379
mybatis-plus:
  mapper-locations: classpath:com/mapper/*.xml
  type-aliases-package: com.example.wpct.entity
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
